// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `adapt_window`, `normalize`, `shift_if_needed`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DanmakuMask>>
abstract class DanmakuMask implements RustOpaqueInterface {
  /// 处理一批文本，返回 Vec<u8>：1 表示允许，0 表示被屏蔽
  Future<Uint8List> allowListBatch(
      {required List<String> texts, required BigInt nowMs});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<DanmakuMask> newInstance(
          {required BigInt baseWindowMs,
          required BigInt bucketCount,
          required bool useNormalization,
          required bool useFrequencyControl,
          required int maxFrequency,
          required bool adaptiveWindow}) =>
      RustLib.instance.api.crateApiDanmakuMaskDanmakuMaskNew(
          baseWindowMs: baseWindowMs,
          bucketCount: bucketCount,
          useNormalization: useNormalization,
          useFrequencyControl: useFrequencyControl,
          maxFrequency: maxFrequency,
          adaptiveWindow: adaptiveWindow);

  Future<void> reset();
}
