// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `adapt_window`, `normalize`, `shift_if_needed`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DanmakuMask>>
abstract class DanmakuMask implements RustOpaqueInterface {
  /// 批量判断是否允许
  /// 返回 Vec<u8>：1 = 允许，0 = 屏蔽
  Future<Uint8List> allowListBatch(
      {required List<String> texts, required BigInt nowMs});

  @override
  void dispose();

  /// 构造函数（会生成 Dart 构造器）
  factory DanmakuMask(
          {required int baseWindowMs,
          required int bucketCount,
          required bool useNormalization,
          required bool useFrequencyControl,
          required int maxFrequency,
          required bool adaptiveWindow}) =>
      RustLib.instance.api.crateApiDanmakuMaskDanmakuMaskNew(
          baseWindowMs: baseWindowMs,
          bucketCount: bucketCount,
          useNormalization: useNormalization,
          useFrequencyControl: useFrequencyControl,
          maxFrequency: maxFrequency,
          adaptiveWindow: adaptiveWindow);

  /// 重置状态
  void reset();
}
