import 'dart:convert';
import 'dart:math' as math;
import 'package:dio/dio.dart';
import 'package:cookie_jar/cookie_jar.dart';
import 'package:dio_cookie_manager/dio_cookie_manager.dart';
import 'package:simple_live_core/src/common/http_client.dart';
import 'package:simple_live_core/src/common/kuaishou_live_link.dart';
import 'package:simple_live_core/src/danmaku/kuaishou_danmaku.dart';
import 'package:simple_live_core/src/interface/live_danmaku.dart';
import 'package:simple_live_core/src/interface/live_site.dart';
import 'package:simple_live_core/src/model/live_anchor_item.dart';
import 'package:simple_live_core/src/model/live_category.dart';
import 'package:simple_live_core/src/model/live_category_result.dart';
import 'package:simple_live_core/src/model/live_play_quality.dart';
import 'package:simple_live_core/src/model/live_play_url.dart';
import 'package:simple_live_core/src/model/live_room_detail.dart';
import 'package:simple_live_core/src/model/live_room_item.dart';
import 'package:simple_live_core/src/model/live_search_result.dart';

class KuaishouSite extends LiveSite {
  static const String userAgent =
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
  KuaishouSite() {
    id = "kuaishou";
    name = "快手直播";
  }

  /// 可选的自定义 Cookie
  String customCookie = '';

  /// The kwfv1 value generated by the Kuaishou web client.
  String customKww = '';

  String cookie = '';
  Map<String, String> cookieObj = {};

  static const List<String> _imageExtensions = [
    'svgz',
    'pjp',
    'png',
    'ico',
    'avif',
    'tiff',
    'tif',
    'jfif',
    'svg',
    'xbm',
    'pjpeg',
    'webp',
    'jpg',
    'jpeg',
    'bmp',
    'gif',
  ];

  Map<String, dynamic> get _headers => {
    'User-Agent': userAgent,
    'accept':
        'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'connection': 'keep-alive',
    'sec-ch-ua': 'Google Chrome;v=120, Chromium;v=120, Not=A?Brand;v=24',
    'sec-ch-ua-platform': 'Windows',
    'Sec-Fetch-Dest': 'document',
    'Sec-Fetch-Mode': 'navigate',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-Fetch-User': '?1',
  };

  Map<String, dynamic> _searchHeaders(String keyword) => {
    ..._headersWithCookie,
    'accept': 'application/json, text/plain, */*',
    'referer':
        'https://live.kuaishou.com/search?keyword=${Uri.encodeComponent(keyword)}',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
  };

  Map<String, dynamic> get _headersWithCookie {
    final headers = <String, dynamic>{..._headers};
    final cookieValue = _currentCookieHeader();
    if (cookieValue.isNotEmpty) {
      headers['cookie'] = cookieValue;
    }
    return headers;
  }

  static String resolveServerKww(String cookie, String fallback) {
    for (final part in cookie.split(';')) {
      final item = part.trim();
      if (!item.startsWith('kwfv1=')) {
        continue;
      }
      final value = item.substring('kwfv1='.length).trim();
      if (value.isEmpty) {
        continue;
      }
      try {
        return '${Uri.decodeComponent(value)}###ssrc';
      } catch (_) {
        return '$value###ssrc';
      }
    }
    return fallback.trim();
  }

  static String resolveRoomTitle(Map room) {
    final liveStream = room["liveStream"] is Map
        ? room["liveStream"] as Map
        : const {};
    final gameInfo = room["gameInfo"] is Map
        ? room["gameInfo"] as Map
        : const {};
    final author = room["author"] is Map ? room["author"] as Map : const {};
    for (final value in [
      room["caption"],
      room["title"],
      liveStream["caption"],
      liveStream["title"],
      gameInfo["name"],
      author["name"],
    ]) {
      final title = value?.toString().trim() ?? '';
      if (title.isNotEmpty) {
        return title;
      }
    }
    return '';
  }

  static Map? selectLiveRoomFromPlayList(
    Iterable<dynamic> playList,
    String roomId,
  ) {
    final rooms = playList.whereType<Map>().toList(growable: false);
    if (rooms.isEmpty) {
      return null;
    }
    final targetRoomId = roomId.trim();
    final matchingRooms = targetRoomId.isEmpty
        ? rooms
        : rooms
              .where((room) => _matchesRoomId(room, targetRoomId))
              .toList(growable: false);
    final candidates = matchingRooms.isEmpty ? rooms : matchingRooms;
    return candidates.firstWhere(
      resolveLiveStatus,
      orElse: () => candidates.first,
    );
  }

  static bool resolveLiveStatus(Map room) {
    if (_isLiveFlag(room["isLiving"]) || _isLiveFlag(room["living"])) {
      return true;
    }
    final liveStream = room["liveStream"] is Map
        ? room["liveStream"] as Map
        : room;
    final liveStreamId = liveStream["id"]?.toString().trim() ?? '';
    // 快手在切换 CDN 或刷新推流地址时会短暂省略 playUrls，但有效的
    // liveStream id 仍代表当前房间正在直播。
    return liveStreamId.isNotEmpty;
  }

  static bool _matchesRoomId(Map room, String roomId) {
    final author = room["author"] is Map ? room["author"] as Map : const {};
    return author["id"]?.toString().trim() == roomId;
  }

  static bool _isLiveFlag(dynamic value) {
    return value == true ||
        value == 1 ||
        value?.toString().toLowerCase() == "true" ||
        value?.toString() == "1";
  }

  @override
  LiveDanmaku getDanmaku() => KuaishouDanmaku();

  // ==================== 分类 ====================

  @override
  Future<List<LiveCategory>> getCategores() async {
    List<LiveCategory> categories = [
      LiveCategory(id: "1", name: "热门", children: []),
      LiveCategory(id: "2", name: "网游", children: []),
      LiveCategory(id: "3", name: "单机", children: []),
      LiveCategory(id: "4", name: "手游", children: []),
      LiveCategory(id: "5", name: "棋牌", children: []),
      LiveCategory(id: "6", name: "娱乐", children: []),
      LiveCategory(id: "7", name: "综合", children: []),
      LiveCategory(id: "8", name: "文化", children: []),
    ];

    for (var category in categories) {
      var subs = await _getAllSubCategories(category);
      category.children.addAll(subs);
    }
    return categories;
  }

  Future<List<LiveSubCategory>> _getAllSubCategories(
    LiveCategory category, {
    int page = 1,
    int pageSize = 30,
  }) async {
    List<LiveSubCategory> allSubs = [];
    try {
      while (true) {
        var subs = await _getSubCategories(category, page, pageSize);
        allSubs.addAll(subs);
        if (subs.length < pageSize) break;
        page++;
      }
    } catch (_) {}
    return allSubs;
  }

  Future<List<LiveSubCategory>> _getSubCategories(
    LiveCategory category,
    int page,
    int pageSize,
  ) async {
    var result = await HttpClient.instance.getJson(
      "https://live.kuaishou.com/live_api/category/data",
      queryParameters: {"type": category.id, "page": page, "size": pageSize},
      header: _headers,
    );

    List<LiveSubCategory> subs = [];
    for (var item in result["data"]["list"] ?? []) {
      subs.add(
        LiveSubCategory(
          id: item["id"].toString(),
          name: item["name"] ?? "",
          parentId: category.id,
          pic: item["poster"],
        ),
      );
    }
    return subs;
  }

  // ==================== 分类直播间列表 ====================

  @override
  Future<LiveCategoryResult> getCategoryRooms(
    LiveSubCategory category, {
    int page = 1,
  }) async {
    var api = category.id.length < 7
        ? "https://live.kuaishou.com/live_api/gameboard/list"
        : "https://live.kuaishou.com/live_api/non-gameboard/list";

    var result = await HttpClient.instance.getJson(
      api,
      queryParameters: {
        "filterType": 0,
        "pageSize": 20,
        "gameId": category.id,
        "page": page,
      },
      header: _headers,
    );

    var items = <LiveRoomItem>[];
    for (var item in result["data"]["list"] ?? []) {
      var cover = item['poster']?.toString() ?? '';
      if (cover.isNotEmpty && !_isImage(cover)) {
        cover = '$cover.jpg';
      }
      items.add(
        LiveRoomItem(
          roomId: item["author"]["id"]?.toString() ?? '',
          title: item['caption']?.toString() ?? '',
          cover: cover,
          userName: item["author"]["name"]?.toString() ?? '',
          online: _parseInt(item["watchingCount"]),
        ),
      );
    }

    return LiveCategoryResult(hasMore: items.length >= 20, items: items);
  }

  // ==================== 推荐直播间 ====================

  @override
  Future<LiveCategoryResult> getRecommendRooms({int page = 1}) async {
    var result = await HttpClient.instance.getJson(
      "https://live.kuaishou.com/live_api/home/list",
      header: _headers,
    );

    var list = result['data']['list'] ?? [];
    var items = <LiveRoomItem>[];

    for (var item in list) {
      for (var sitem in item["gameLiveInfo"] ?? []) {
        for (var titem in sitem["liveInfo"] ?? []) {
          var author = titem["author"];
          var gameInfo = titem["gameInfo"];
          var cover = gameInfo['poster']?.toString() ?? '';
          items.add(
            LiveRoomItem(
              roomId: author["id"]?.toString() ?? '',
              title: resolveRoomTitle(titem),
              cover: cover,
              userName: author["name"]?.toString() ?? '',
              online: _parseInt(titem["watchingCount"]),
            ),
          );
        }
      }
    }
    if (items.any((item) => item.online > 0)) {
      items.sort((a, b) => b.online.compareTo(a.online));
    }

    return LiveCategoryResult(hasMore: false, items: items);
  }

  // ==================== 搜索 ====================

  @override
  Future<LiveSearchRoomResult> searchRooms(
    String keyword, {
    int page = 1,
  }) async {
    try {
      var result = await _searchLiveStreams(keyword, page: page);
      if (result.items.isNotEmpty || page > 1) {
        return result;
      }
    } catch (_) {}

    if (page > 1) {
      return LiveSearchRoomResult(hasMore: false, items: <LiveRoomItem>[]);
    }

    try {
      return await _searchRoomsByOverview(keyword);
    } catch (_) {
      return LiveSearchRoomResult(hasMore: false, items: <LiveRoomItem>[]);
    }
  }

  Future<LiveSearchRoomResult> _searchLiveStreams(
    String keyword, {
    int page = 1,
  }) async {
    var result = await HttpClient.instance.getJson(
      "https://live.kuaishou.com/live_api/search/liveStream",
      queryParameters: {"keyword": keyword, "page": page, "ussid": ""},
      header: _searchHeaders(keyword),
    );

    var data = result["data"];
    if (data is! Map || data["result"] != 1) {
      return LiveSearchRoomResult(hasMore: false, items: <LiveRoomItem>[]);
    }

    var list = (data["list"] as List?) ?? [];
    var items = <LiveRoomItem>[];
    for (var item in list) {
      var room = _parseSearchLiveRoom(item);
      if (room.roomId.isNotEmpty) {
        items.add(room);
      }
    }

    return LiveSearchRoomResult(hasMore: list.isNotEmpty, items: items);
  }

  Future<LiveSearchRoomResult> _searchRoomsByOverview(String keyword) async {
    var overview = await _getSearchOverview(keyword);
    var liveStreams = overviewLiveStreams(overview);
    var items = <LiveRoomItem>[];
    for (var item in liveStreams) {
      var room = _parseSearchLiveRoom(item);
      if (room.roomId.isNotEmpty) {
        items.add(room);
      }
    }
    if (items.isNotEmpty) {
      return LiveSearchRoomResult(hasMore: false, items: items);
    }
    return LiveSearchRoomResult(hasMore: false, items: <LiveRoomItem>[]);
  }

  static List<dynamic> overviewLiveStreams(Map overview) {
    final sections = overview["list"];
    if (sections is! List) {
      return const <dynamic>[];
    }
    for (final section in sections) {
      if (section is Map && section["type"] == "liveStreams") {
        final items = section["list"];
        return items is List ? List<dynamic>.from(items) : const <dynamic>[];
      }
    }
    return const <dynamic>[];
  }

  @override
  Future<LiveSearchAnchorResult> searchAnchors(
    String keyword, {
    int page = 1,
  }) async {
    try {
      var result = await _searchAnchors(keyword, page: page);
      if (result.items.isNotEmpty || page > 1) {
        return result;
      }
    } catch (_) {}

    if (page > 1) {
      return LiveSearchAnchorResult(hasMore: false, items: <LiveAnchorItem>[]);
    }

    try {
      var overview = await _getSearchOverview(keyword);
      var authors = _findOverviewSectionList(overview, "authors");
      var items = <LiveAnchorItem>[];
      for (var item in authors) {
        var anchor = _parseSearchAnchor(item);
        if (anchor.roomId.isNotEmpty) {
          items.add(anchor);
        }
      }
      return LiveSearchAnchorResult(hasMore: false, items: items);
    } catch (_) {
      return LiveSearchAnchorResult(hasMore: false, items: <LiveAnchorItem>[]);
    }
  }

  Future<LiveSearchAnchorResult> _searchAnchors(
    String keyword, {
    int page = 1,
  }) async {
    var result = await HttpClient.instance.getJson(
      "https://live.kuaishou.com/live_api/search/author",
      queryParameters: {
        "key": keyword,
        "keyword": keyword,
        "page": page,
        "count": 15,
        "ussid": "",
        "lssid": "",
      },
      header: _searchHeaders(keyword),
    );

    var data = result["data"];
    if (data is! Map || data["result"] != 1) {
      return LiveSearchAnchorResult(hasMore: false, items: <LiveAnchorItem>[]);
    }

    var list = (data["list"] as List?) ?? [];
    var items = <LiveAnchorItem>[];
    for (var item in list) {
      var anchor = _parseSearchAnchor(item);
      if (anchor.roomId.isNotEmpty) {
        items.add(anchor);
      }
    }

    return LiveSearchAnchorResult(hasMore: list.length >= 15, items: items);
  }

  Future<Map> _getSearchOverview(String keyword) async {
    var result = await HttpClient.instance.getJson(
      "https://live.kuaishou.com/live_api/search/overview",
      queryParameters: {"keyword": keyword, "ussid": ""},
      header: _searchHeaders(keyword),
    );
    var data = result["data"];
    return data is Map ? data : <String, dynamic>{};
  }

  List _findOverviewSectionList(Map overview, String type) {
    var sections = overview["list"];
    if (sections is! List) {
      return [];
    }
    for (var section in sections) {
      if (section is Map && section["type"] == type) {
        return (section["list"] as List?) ?? [];
      }
    }
    return [];
  }

  LiveRoomItem _parseSearchLiveRoom(dynamic item) {
    if (item is! Map) {
      return LiveRoomItem(roomId: '', title: '', cover: '', userName: '');
    }

    var author = item["author"] is Map ? item["author"] as Map : {};
    var gameInfo = item["gameInfo"] is Map ? item["gameInfo"] as Map : {};
    var cover =
        item["poster"]?.toString() ??
        item["coverUrl"]?.toString() ??
        gameInfo["poster"]?.toString() ??
        '';
    if (cover.isNotEmpty && !_isImage(cover)) {
      cover = '$cover.jpg';
    }

    return LiveRoomItem(
      roomId:
          author["id"]?.toString() ??
          item["authorId"]?.toString() ??
          item["userId"]?.toString() ??
          '',
      title:
          item["caption"]?.toString() ??
          item["title"]?.toString() ??
          author["name"]?.toString() ??
          '',
      cover: cover,
      userName:
          author["name"]?.toString() ?? item["userName"]?.toString() ?? '',
      online: _parseInt(item["watchingCount"]),
    );
  }

  LiveAnchorItem _parseSearchAnchor(dynamic item) {
    if (item is! Map) {
      return LiveAnchorItem(
        roomId: '',
        avatar: '',
        userName: '',
        liveStatus: false,
      );
    }

    return LiveAnchorItem(
      roomId: item["id"]?.toString() ?? '',
      avatar: item["avatar"]?.toString() ?? '',
      userName: item["name"]?.toString() ?? '',
      liveStatus: item["living"] == true,
    );
  }

  // ==================== 房间详情 ====================

  @override
  Future<LiveRoomDetail> getRoomDetail({required String roomId}) async {
    final url = "https://live.kuaishou.com/u/$roomId";

    await _getCookie(url);
    await _registerDid();

    final anonymousDetail = await _loadRoomDetail(
      url: url,
      roomId: roomId,
      headers: _headers,
    );
    if (anonymousDetail?.status == true) {
      return anonymousDetail!;
    }

    LiveRoomDetail? cookieDetail;
    if (_currentCookieHeader().isNotEmpty) {
      cookieDetail = await _loadRoomDetail(
        url: url,
        roomId: roomId,
        headers: _headersWithCookie,
      );
      if (cookieDetail != null &&
          (cookieDetail.status || anonymousDetail == null)) {
        return cookieDetail;
      }
    }

    if (anonymousDetail != null) {
      return anonymousDetail;
    }
    if (cookieDetail != null) {
      return cookieDetail;
    }
    throw StateError("快手直播间状态暂时不可用");
  }

  Future<LiveRoomDetail?> _loadRoomDetail({
    required String url,
    required String roomId,
    required Map<String, dynamic> headers,
  }) async {
    try {
      final resultText = await HttpClient.instance.getText(
        url,
        queryParameters: const {},
        header: headers,
      );
      return await _parseRoomDetail(resultText, roomId);
    } catch (_) {
      return null;
    }
  }

  Future<LiveRoomDetail?> _parseRoomDetail(
    String resultText,
    String roomId,
  ) async {
    try {
      final text = RegExp(
        r"window\.__INITIAL_STATE__=(.*?);",
        multiLine: false,
      ).firstMatch(resultText)?.group(1);
      if (text == null) {
        return null;
      }

      final transferData = text.replaceAll("undefined", "null");
      final jsonObj = jsonDecode(transferData);
      if (jsonObj is! Map || jsonObj["liveroom"] is! Map) {
        return null;
      }
      final liveroom = jsonObj["liveroom"] as Map;
      final playList = liveroom["playList"];
      if (playList is! List) {
        return null;
      }
      if (playList.isEmpty) {
        return _offlineDetail(roomId);
      }

      final first = selectLiveRoomFromPlayList(playList, roomId);
      if (first == null) {
        return null;
      }
      final liveStream = first["liveStream"] is Map
          ? first["liveStream"] as Map
          : const {};
      final author = first["author"] is Map ? first["author"] as Map : const {};
      final gameInfo = first["gameInfo"] is Map
          ? first["gameInfo"] as Map
          : const {};
      final isLiving = resolveLiveStatus(first);
      final liveStreamId = liveStream["id"]?.toString() ?? '';
      var websocketUrls = <String>[];
      for (final item in liveroom["websocketUrls"] ?? []) {
        final websocketUrl = item?.toString() ?? '';
        if (websocketUrl.isNotEmpty) {
          websocketUrls.add(websocketUrl);
        }
      }
      var danmakuToken = liveroom["token"]?.toString() ?? '';
      final websocketInfo = first["websocketInfo"] is Map
          ? first["websocketInfo"] as Map
          : const {};
      if (danmakuToken.isEmpty) {
        danmakuToken = websocketInfo["token"]?.toString() ?? '';
      }
      if (websocketUrls.isEmpty) {
        for (final item
            in websocketInfo["websocketUrls"] ??
                websocketInfo["webSocketAddresses"] ??
                const []) {
          final websocketUrl = item?.toString() ?? '';
          if (websocketUrl.isNotEmpty) {
            websocketUrls.add(websocketUrl);
          }
        }
      }
      if (isLiving &&
          liveStreamId.isNotEmpty &&
          (danmakuToken.isEmpty || websocketUrls.isEmpty)) {
        final info = await _getWebsocketInfo(
          roomId: author["id"]?.toString() ?? roomId,
          liveStreamId: liveStreamId,
        );
        danmakuToken = info.token.isNotEmpty ? info.token : danmakuToken;
        if (websocketUrls.isEmpty) {
          websocketUrls = info.websocketUrls;
        }
      }

      var cover = liveStream["poster"]?.toString() ?? '';
      if (cover.isNotEmpty && !_isImage(cover)) {
        cover = '$cover.jpg';
      }

      return LiveRoomDetail(
        roomId: author["id"]?.toString() ?? roomId,
        title: resolveRoomTitle(first),
        cover: cover,
        userName: author["name"]?.toString() ?? '',
        userAvatar: author["avatar"]?.toString() ?? '',
        online: isLiving ? _parseInt(gameInfo["watchingCount"]) : 0,
        introduction: author["description"]?.toString(),
        notice: author["description"]?.toString(),
        status: isLiving,
        url:
            KuaishouLiveLink.publicRoomUri(
              author["id"]?.toString() ?? roomId,
            )?.toString() ??
            "https://live.kuaishou.com/u/$roomId",
        data: liveStream["playUrls"],
        danmakuData: KuaishouDanmakuArgs(
          roomId: author["id"]?.toString() ?? roomId,
          liveStreamId: liveStreamId,
          token: danmakuToken,
          websocketUrls: websocketUrls,
          pageId: _generatePageId(),
          expTag: liveStream["expTag"]?.toString() ?? '',
          attach: first["expTag"]?.toString() ?? '',
          cookie: _currentCookieHeader(),
          userAgent: userAgent,
        ),
        categoryId: gameInfo["id"]?.toString(),
        categoryName: gameInfo["name"]?.toString(),
      );
    } catch (_) {
      return null;
    }
  }

  LiveRoomDetail _offlineDetail(String roomId) {
    return LiveRoomDetail(
      roomId: roomId,
      title: '',
      cover: '',
      userName: '',
      userAvatar: '',
      online: 0,
      status: false,
      url: '',
    );
  }

  @override
  Future<bool> getLiveStatus({required String roomId}) async {
    final detail = await getRoomDetail(roomId: roomId);
    return detail.status;
  }

  // ==================== 清晰度 ====================

  @override
  Future<List<LivePlayQuality>> getPlayQualites({
    required LiveRoomDetail detail,
  }) async {
    List<LivePlayQuality> qualities = [];

    try {
      var qualityList = detail.data["h264"]["adaptationSet"]["representation"];

      for (var quality in qualityList ?? []) {
        qualities.add(
          LivePlayQuality(
            quality: quality["name"]?.toString() ?? '',
            sort: quality["level"] ?? 0,
            data: <String>[quality["url"]?.toString() ?? ''],
          ),
        );
      }
    } catch (_) {}

    qualities.sort((a, b) => b.sort.compareTo(a.sort));
    return qualities;
  }

  @override
  Future<LivePlayUrl> getPlayUrls({
    required LiveRoomDetail detail,
    required LivePlayQuality quality,
  }) async {
    List<String> urls = [];
    if (quality.data is List) {
      for (var item in quality.data) {
        urls.add(item.toString());
      }
    }
    return LivePlayUrl(urls: urls);
  }

  // ==================== Cookie 管理 ====================

  Future<void> _getCookie(String url) async {
    try {
      final dio = Dio();
      final cookieJar = CookieJar();
      dio.interceptors.add(CookieManager(cookieJar));
      await dio.get(url, options: Options(headers: _headersWithCookie));
      List<Cookie> cookies = await cookieJar.loadForRequest(Uri.parse(url));
      final cookieValues = _parseCookieHeader(customCookie);
      for (var i = 0; i < cookies.length; i++) {
        cookieValues[cookies[i].name] = cookies[i].value;
      }
      cookieObj = cookieValues;
      cookie = _formatCookieHeader(cookieValues);
    } catch (_) {
      cookieObj = _parseCookieHeader(customCookie);
      cookie = _formatCookieHeader(cookieObj);
    }
  }

  Future<_KuaishouWebsocketInfo> _getWebsocketInfo({
    required String roomId,
    required String liveStreamId,
  }) async {
    try {
      final kww = resolveServerKww(_currentCookieHeader(), customKww);
      final result = await HttpClient.instance.getJson(
        "https://live.kuaishou.com/live_api/liveroom/websocketinfo",
        queryParameters: {"liveStreamId": liveStreamId},
        header: {
          ..._headersWithCookie,
          if (kww.isNotEmpty) 'Kww': kww,
          'accept': 'application/json, text/plain, */*',
          'referer': 'https://live.kuaishou.com/u/$roomId',
          'Sec-Fetch-Dest': 'empty',
          'Sec-Fetch-Mode': 'cors',
        },
      );
      final data = result["data"];
      if (data is! Map) {
        return _KuaishouWebsocketInfo.empty();
      }
      final urls = <String>[];
      final websocketUrls =
          data["websocketUrls"] ??
          data["webSocketAddresses"] ??
          const <dynamic>[];
      for (final item in websocketUrls) {
        final url = item?.toString() ?? '';
        if (url.isNotEmpty) {
          urls.add(url);
        }
      }
      return _KuaishouWebsocketInfo(
        token: data["token"]?.toString() ?? '',
        websocketUrls: urls,
      );
    } catch (e) {
      return _KuaishouWebsocketInfo.empty();
    }
  }

  // ==================== DID 注册 ====================

  Future<void> _registerDid() async {
    var did = cookieObj['did'];
    if (did == null || did.isEmpty) return;
    try {
      await HttpClient.instance.postJson(
        'https://log-sdk.ksapisrv.com/rest/wd/common/log/collect/misc2?v=3.9.49&kpn=KS_GAME_LIVE_PC',
        header: _headers,
        data: _buildMisc2Data(did),
      );
    } catch (_) {}
  }

  Map<String, dynamic> _buildMisc2Data(String did) {
    return {
      'common': {
        'identity_package': {'device_id': did, 'global_id': ''},
        'app_package': {
          'language': 'zh-CN',
          'platform': 10,
          'container': 'WEB',
          'product_name': 'KS_GAME_LIVE_PC',
        },
        'device_package': {
          'os_version': 'NT 10.0',
          'model': 'Windows',
          'ua':
              'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        },
        'need_encrypt': 'false',
        'network_package': {'type': 3},
        'h5_extra_attr':
            '{"sdk_name":"webLogger","sdk_version":"3.9.49","sdk_bundle":"log.common.js","app_version_name":"","host_product":"","resolution":"1920x1080","screen_with":1920,"screen_height":1080,"device_pixel_ratio":1,"domain":"https://live.kuaishou.com"}',
        'global_attr': '{}',
      },
      'logs': [
        {
          'client_timestamp': DateTime.now().millisecondsSinceEpoch,
          'client_increment_id': math.Random().nextInt(8999) + 1000,
          'session_id': _generateSessionId(),
          'time_zone': 'GMT+08:00',
          'event_package': {
            'task_event': {
              'type': 1,
              'status': 0,
              'operation_type': 1,
              'operation_direction': 0,
              'session_id': _generateSessionId(),
              'url_package': {
                'page': 'GAME_DETAL_PAGE',
                'identity': _generateUuid(),
                'page_type': 2,
                'params': '{"game_id":1001,"game_name":"王者荣耀"}',
              },
              'element_package': {},
            },
          },
        },
      ],
    };
  }

  String _generateSessionId() {
    return '${_hex(8)}-${_hex(4)}-${_hex(4)}-${_hex(4)}-${_hex(12)}';
  }

  String _generateUuid() {
    return '${_hex(8)}-${_hex(4)}-${_hex(4)}-${_hex(4)}-${_hex(12)}';
  }

  String _generatePageId() {
    const chars =
        'useandom-26T198340PX75pxJACKVERYMINDBUSHWOLF_GQZbfghjklqvwyzrict';
    final random = math.Random();
    return List.generate(16, (_) => chars[random.nextInt(chars.length)]).join();
  }

  String _hex(int length) {
    const chars = '0123456789abcdef';
    var result = '';
    for (var i = 0; i < length; i++) {
      result += chars[math.Random().nextInt(16)];
    }
    return result;
  }

  // ==================== 工具方法 ====================

  bool _isImage(String url) {
    if (url.isEmpty) return false;
    var ext = url.split('.').last.toLowerCase();
    return _imageExtensions.contains(ext);
  }

  int _parseInt(dynamic value) {
    if (value == null) return 0;
    if (value is int) return value;
    if (value is String) return int.tryParse(value) ?? 0;
    if (value is double) return value.toInt();
    return 0;
  }

  String _currentCookieHeader() {
    return customCookie.isNotEmpty
        ? _mergeCookie(customCookie, cookie)
        : cookie;
  }

  String _mergeCookie(String baseCookie, String extraCookie) {
    final values = _parseCookieHeader(baseCookie);
    values.addAll(_parseCookieHeader(extraCookie));
    return _formatCookieHeader(values);
  }

  Map<String, String> _parseCookieHeader(String cookie) {
    final result = <String, String>{};
    for (final part in cookie.split(';')) {
      final item = part.trim();
      if (item.isEmpty) {
        continue;
      }
      final index = item.indexOf('=');
      if (index <= 0) {
        continue;
      }
      final key = item.substring(0, index).trim();
      final value = item.substring(index + 1).trim();
      if (key.isNotEmpty && value.isNotEmpty) {
        result[key] = value;
      }
    }
    return result;
  }

  String _formatCookieHeader(Map<String, String> values) {
    return values.entries.map((e) => '${e.key}=${e.value}').join('; ');
  }
}

class _KuaishouWebsocketInfo {
  final String token;
  final List<String> websocketUrls;

  _KuaishouWebsocketInfo({required this.token, required this.websocketUrls});

  factory _KuaishouWebsocketInfo.empty() {
    return _KuaishouWebsocketInfo(token: '', websocketUrls: <String>[]);
  }
}
